name: Cache

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - solaire
          - vamos
          - anastacia
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/cachix/install-nix-action@v31
        with:
          extra_nix_config: |-
            accept-flake-config = true
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
