name: Cache

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: native
    strategy:
      matrix:
        host:
          - solaire
          - vamos
          - anastacia
    steps:
      - uses: actions/checkout@v4
      - run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
