name: Cache hosts
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: native
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run checks
        run: |
          nix flake check \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --accept-flake-config

  build:
    runs-on: native
    strategy:
      matrix:
        host:
          - solaire
          - vamos
          - anastacia
    name: Build ${{ matrix.host }}
    needs: [check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          nix build \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --accept-flake-config \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --out-link "$HOME/${{ matrix.host }}"
