name: Cache

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: native
    strategy:
      matrix:
        host:
          - solaire
          - vamos
          - anastacia
    steps:
      - uses: actions/checkout@v4
      - run: |
          nix build \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --accept-flake-config ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --out-link "$HOME/${{ matrix.host }}" # predictable location and separate hostnames to avoid gc
