{
  imports = [
    ./brightness.nix
    ./docker.nix
    ./documentation.nix
    ./flatpak.nix
    ./forgejo.nix
    ./gnome.nix
    ./gnupg.nix
    ./greetd.nix
    ./keyd.nix
    ./kmscon.nix
    ./location.nix
    ./logind.nix
    ./pipewire.nix
    ./power.nix
    ./searx.nix
    ./syncthing.nix
    ./website.nix
  ];
}
