name: Cache

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - "Update sources"
    types:
      - completed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - solaire
          - vamos
          - anastacia
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |-
            accept-flake-config = true
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Attic
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}
      - run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
