name: Update sources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # every sunday at midnight
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Install Nix"
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Update npins"
        run: |
          cd parts || exit
          nix run nixpkgs#npins update
      - name: "Update flake"
        run: nix flake update
      - name: "Commit Changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: GitHub Actions
          commit_message: "[CI]: update inputs"
          commit_options: "--no-verify --signoff"
          push_options: "--force"
